### ISSUE TITLE
Gallery submission feedback - Google Merchant Center Lookup

### ISSUE THREAD

**Issue by nataliecraun** [stape-io/merchant-center-variable#1]
**Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run**

When reviewing your template, we've noticed that `gtmOnSuccess` or `gtmOnFailure` are called incorrectly. This is required so that users can sequence their tags correctly.

**Comment by Bukashk0zzz** [comment]
@nataliecraun this is Variable not a tag.

For variables calling gtmOnSuccess or gtmOnFailure is not needed.

**Comment by nataliecraun** [comment]
Can you update the title of the variable to follow the format **[company name] [tag name]** or **[tag name] by [company name])**

**Comment by Bukashk0zzz** [comment]
Tag is renamed.
Check https://github.com/stape-io/merchant-center-variable/commit/33ccaa56e9730ebdcac4f35fcd78b2da974053e9

**Comment by nataliecraun** [comment]
Sorry for the confusion, it should be your company name.

**Comment by Bukashk0zzz** [comment]
@nataliecraun 
Updated https://github.com/stape-io/merchant-center-variable/commit/7b015ccf9d048d0c41f60ec27cae8d23cdc136e4
